# Numpy - "Numerical pyhton"
<pre> numpy is a pyhton library 's library which is use to perform different mathematical operations on arrays 

Array is denoted with '[]' it is ordered (index position is fixed ), mutable (items can be modified) and homogenous (items of similar datatypes)collections of items .</pre>

In [1]:
import numpy as np


In [2]:
np.__version__


'2.3.5'

In [5]:
#creating 1D Array
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
type(a) #ndarray : n-dimentional array

numpy.ndarray

In [7]:
a  = np.array([23,'cat',True,2.4])
a

array(['23', 'cat', 'True', '2.4'], dtype='<U32')

In [10]:
# tuple to array 
t = np.array((12,34,65,76)) 
t

array([12, 34, 65, 76])

In [11]:
#set to array
s = np.array({23,34,45,5,})
s

array({34, 45, 5, 23}, dtype=object)

In [12]:
#dictionary to array
d = np.array({'a':1,'b':2,'c':3})
d

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [14]:
#dictionary to array
d = np.array({'a':10,'b':20,'c':13})
d

array({'a': 10, 'b': 20, 'c': 13}, dtype=object)

In [2]:
import numpy as np


In [5]:
#creating 2D array
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b = np.array([[1,2,3,0],[4,5,6,0],[7,8,9,0]])
b

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0]])

In [13]:
#Array Attributes
b.shape

(3, 4)

In [14]:
b.size

12

In [15]:
# number of dimensions
b.ndim

2

In [22]:
a = np.array([1,2],ndmin=64)
print(a)
a.ndim

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1
                                                                2]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


64

In [25]:
# Arrange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [27]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [28]:
#zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
np.zeros((5,5)).astype(int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [44]:
#one
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [48]:
#full 
np.full((5,5),'😒',)

array([['😒', '😒', '😒', '😒', '😒'],
       ['😒', '😒', '😒', '😒', '😒'],
       ['😒', '😒', '😒', '😒', '😒'],
       ['😒', '😒', '😒', '😒', '😒'],
       ['😒', '😒', '😒', '😒', '😒']], dtype='<U1')

In [49]:
#eye-identity matrix
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [59]:
# linspace - equaly distributed numbers
np.linspace(1,100,100)


array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [61]:
#rendom numbers
np.random.rand(5)

array([0.05194984, 0.92186603, 0.46874694, 0.24269738, 0.68465127])

In [63]:
np.random.rand(3,4)*100

array([[78.72614468, 69.35472694, 99.82879664, 38.3660326 ],
       [ 0.30174974,  0.7035856 , 43.06624603, 48.13673694],
       [66.53304202, 24.83260625, 37.12980951,  2.95394721]])

In [68]:
np.random.randint(1,32)

25

In [69]:
np.random.randint(1,20,(5,5))

array([[10, 18,  4,  1, 10],
       [10, 10, 16, 11, 12],
       [18, 18, 11,  4, 15],
       [ 6,  2, 13, 10,  8],
       [ 2, 10, 12,  8, 14]], dtype=int32)