# Numpy - "Numerical pyhton"
<pre> numpy is a pyhton library 's library which is use to perform different mathematical operations on arrays 

Array is denoted with '[]' it is ordered (index position is fixed ), mutable (items can be modified) and homogenous (items of similar datatypes)collections of items .</pre>

In [1]:
import numpy as np


In [2]:
np.__version__


'2.3.5'

In [5]:
#creating 1D Array
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
type(a) #ndarray : n-dimentional array

numpy.ndarray

In [7]:
a  = np.array([23,'cat',True,2.4])
a

array(['23', 'cat', 'True', '2.4'], dtype='<U32')

In [10]:
# tuple to array 
t = np.array((12,34,65,76)) 
t

array([12, 34, 65, 76])

In [11]:
#set to array
s = np.array({23,34,45,5,})
s

array({34, 45, 5, 23}, dtype=object)

In [12]:
#dictionary to array
d = np.array({'a':1,'b':2,'c':3})
d

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [14]:
#dictionary to array
d = np.array({'a':10,'b':20,'c':13})
d

array({'a': 10, 'b': 20, 'c': 13}, dtype=object)

In [2]:
import numpy as np


In [5]:
#creating 2D array
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b = np.array([[1,2,3,0],[4,5,6,0],[7,8,9,0]])
b

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0]])

In [13]:
#Array Attributes
b.shape

(3, 4)

In [14]:
b.size

12

In [15]:
# number of dimensions
b.ndim

2

In [22]:
a = np.array([1,2],ndmin=64)
print(a)
a.ndim

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1
                                                                2]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


64

In [25]:
# Arrange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [27]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [28]:
#zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
np.zeros((5,5)).astype(int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [44]:
#one
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [48]:
#full 
np.full((5,5),'😒',)

array([['😒', '😒', '😒', '😒', '😒'],
       ['😒', '😒', '😒', '😒', '😒'],
       ['😒', '😒', '😒', '😒', '😒'],
       ['😒', '😒', '😒', '😒', '😒'],
       ['😒', '😒', '😒', '😒', '😒']], dtype='<U1')

In [49]:
#eye-identity matrix
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [59]:
# linspace - equaly distributed numbers
np.linspace(1,100,100)


array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [61]:
#rendom numbers
np.random.rand(5)

array([0.05194984, 0.92186603, 0.46874694, 0.24269738, 0.68465127])

In [63]:
np.random.rand(3,4)*100

array([[78.72614468, 69.35472694, 99.82879664, 38.3660326 ],
       [ 0.30174974,  0.7035856 , 43.06624603, 48.13673694],
       [66.53304202, 24.83260625, 37.12980951,  2.95394721]])

In [68]:
np.random.randint(1,32)

25

In [69]:
np.random.randint(1,20,(5,5))

array([[10, 18,  4,  1, 10],
       [10, 10, 16, 11, 12],
       [18, 18, 11,  4, 15],
       [ 6,  2, 13, 10,  8],
       [ 2, 10, 12,  8, 14]], dtype=int32)

# mathematical operations

In [71]:
a = np.array([25,83,75,20,55])
b = np.array([4,9,8,2,6])
a
b

array([4, 9, 8, 2, 6])

In [72]:
np.add(a,b)

array([29, 92, 83, 22, 61])

In [73]:
#subtract
np.subtract(a,b)

array([21, 74, 67, 18, 49])

In [74]:
#multiply
np.multiply(a,b)

array([100, 747, 600,  40, 330])

In [77]:
#divide
np.divide(a,b)

array([ 6.25      ,  9.22222222,  9.375     , 10.        ,  9.16666667])

In [78]:
# floor-divide
np.floor_divide(a,b)

array([ 6,  9,  9, 10,  9])

In [79]:
#modulo 
np.mod(a,b)

array([1, 2, 3, 0, 1])

In [ ]:
#divmod          # floor_divide & modulo
np.divmod(a,b)

(array([ 6,  9,  9, 10,  9]), array([1, 2, 3, 0, 1]))

In [81]:
# sqrt - square root
np.sqrt(25)

np.float64(5.0)

In [85]:
# power
np.power(b,2)

array([16, 81, 64,  4, 36])

In [86]:
#log - (bydefault base = 'e')
np.log(a)

array([3.21887582, 4.41884061, 4.31748811, 2.99573227, 4.00733319])

In [87]:
np.log10(a)

array([1.39794001, 1.91907809, 1.87506126, 1.30103   , 1.74036269])

In [88]:
#sin
np.sin(a)

array([-0.13235175,  0.96836446, -0.38778164,  0.91294525, -0.99975517])

In [ ]:
# cos
np.cos(a)

array([0.99120281, 0.24954012, 0.92175127, 0.40808206, 0.02212676])

In [90]:
np.sin(90*(np.pi/180))

np.float64(1.0)

In [91]:
np.tan(a)

array([ -0.13352641,   3.88059631,  -0.42070095,   2.23716094,
       -45.18308791])

In [93]:
# cot
1/np.tan(a)

array([-7.48915531,  0.25769235, -2.37698536,  0.44699511, -0.02213217])

# statistical functions

In [94]:
a

array([25, 83, 75, 20, 55])

In [95]:
#max
np.max(a)

np.int64(83)

In [ ]:
#min
np.min(a)

np.int64(20)

In [97]:
#argmax
np.argmax(a)

np.int64(1)

In [98]:
#argmin
np.argmin(a)

np.int64(3)

In [99]:
#sort
np.sort(a)

array([20, 25, 55, 75, 83])

In [100]:
#argsort
np.argsort(a)

array([3, 0, 4, 2, 1])

In [101]:
#mean
np.mean(a)

np.float64(51.6)

In [102]:
#std --standard deviation
np.std(a)

np.float64(25.499803920814763)

In [103]:
#var - variance
np.var(a)

np.float64(650.24)

In [104]:
#cumsum - cumilative summation
np.cumsum(b)

array([ 4, 13, 21, 23, 29])

In [105]:
#comprod - cumulative product
np.cumprod(b)

array([   4,   36,  288,  576, 3456])

# vector maths

In [107]:
a = np.array([[1,3],[2,4]])
b = np.array([[5,7],[9,8]])
print(a)
print(b)

[[1 3]
 [2 4]]
[[5 7]
 [9 8]]


In [108]:
# dot product
np.dot(a,b)

array([[32, 31],
       [46, 46]])

In [109]:
# cross product
np.cross(a,b)

C:\Users\LOG IN\AppData\Local\Temp\ipykernel_1916\486548216.py:2: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(a,b)


array([ -8, -20])

In [111]:
# repeat
a = np.array([1,2,3,4])
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [113]:
#tile
a = np.array([1,2,3,4])
np.tile(a,4)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [114]:
#where 
a = np.array([1,2,3,4,4,5,6,7,8])
np.where(a==4)

(array([3, 4]),)

In [1]:
import numpy as np


In [2]:
#Indexing & Slicing in 1D Array 
a = np.array([25,78,55,96,35])
a

array([25, 78, 55, 96, 35])

In [3]:
#indexing 
a[2]

np.int64(55)

In [4]:
a[-3]

np.int64(55)

In [5]:
#slicing
a[0:5:2]

array([25, 55, 35])

In [6]:
a[::2]

array([25, 55, 35])

In [7]:
#indexing and slicing in 2D Array
b = np.random.randint(1,20,(5,5))
b

array([[17,  1,  8,  5,  7],
       [11,  2,  4,  1, 17],
       [10, 19, 14,  8, 12],
       [ 7, 19,  8, 18,  5],
       [ 2,  1,  7, 16, 10]], dtype=int32)

In [8]:
#indexing 
#syntex: var[row_index,col_index]
b[2,3]

np.int32(8)

In [ ]:
b[3]   # bydefault row

array([ 7, 19,  8, 18,  5], dtype=int32)

In [ ]:
#slicing
# slicing:-var[start :stop+1 : step ]
b[1:4:1,1:4:1]

array([[ 2,  4,  1],
       [19, 14,  8],
       [19,  8, 18]], dtype=int32)

In [12]:
#all rows and even columns (0,2,4)
#odd rows and odd columns(1,3)
b[0:5:1,0:5:2]

array([[17,  8,  7],
       [11,  4, 17],
       [10, 14, 12],
       [ 7,  8,  5],
       [ 2,  7, 10]], dtype=int32)

In [13]:
b[1:4:2,1:4:2]

array([[ 2,  1],
       [19, 18]], dtype=int32)

In [14]:
#concatinatiion - joining matrix
a = np.random.randint(1,20,(2,2))
a

array([[10, 18],
       [12,  6]], dtype=int32)

In [15]:
b = np.random.randint(1,20,(2,4))
b

array([[ 6, 10, 10, 19],
       [14,  2,  9, 19]], dtype=int32)

In [18]:
c = np.random.randint(1,20,(4,4))
c

array([[14,  9,  9, 18],
       [14,  2, 17, 13],
       [16,  6, 16,  4],
       [13,  1, 14, 15]], dtype=int32)

In [19]:
#column wise (axis = 1)
np.concatenate((a,b),axis=1)

array([[10, 18,  6, 10, 10, 19],
       [12,  6, 14,  2,  9, 19]], dtype=int32)

In [20]:
#row wise (axis=0)(bydefault)
np.concatenate((b,c),axis=0)

array([[ 6, 10, 10, 19],
       [14,  2,  9, 19],
       [14,  9,  9, 18],
       [14,  2, 17, 13],
       [16,  6, 16,  4],
       [13,  1, 14, 15]], dtype=int32)

In [21]:
#stack - joining the matrix
#hstack - jorizontal stack
np.hstack((a,b))

array([[10, 18,  6, 10, 10, 19],
       [12,  6, 14,  2,  9, 19]], dtype=int32)

In [ ]:
#vstack - vertically stack
np.vstack((b,c))

array([[ 6, 10, 10, 19],
       [14,  2,  9, 19],
       [14,  9,  9, 18],
       [14,  2, 17, 13],
       [16,  6, 16,  4],
       [13,  1, 14, 15]], dtype=int32)

# PANDAS🐼
<pre><b>🐼pandas is a python library which is use to analyze and manupulate the data 

it is also use to create and read datasets

its of two types 
1. series(single column)
2. dataframe(multiple columns)</pre>

In [23]:
import pandas as pd

In [30]:
#creating series 
s = pd.Series(['a','b','c','d','e'],index=[10,20,20,40,50])
s

10    a
20    b
20    c
40    d
50    e
dtype: object

In [31]:
s = pd.Series(['a','b','c','d','e'],index=np.arange(10,20,2))
s

10    a
12    b
14    c
16    d
18    e
dtype: object

In [33]:
#indexing
s[16]

'd'

In [35]:
#slicing 
s[1:4:2]

12    b
16    d
dtype: object

In [37]:
#tuple to series 
t = pd.Series((100,200,300,400))
t

0    100
1    200
2    300
3    400
dtype: int64

In [ ]:
#set to series -- we cant set series using set because its unordered

In [38]:
#dictionary to series 
d = pd.Series({'a':1,'b':2,'c':3,'d':4})
d

a    1
b    2
c    3
d    4
dtype: int64

In [43]:
d1=pd.Series({'a':1,'b':2,'c':3,'d':4},index=['e','f','g','h'])
d1

e   NaN
f   NaN
g   NaN
h   NaN
dtype: float64

In [44]:
d1=pd.Series({'a':1,'b':2,'c':3,'d':4},index=['a','b','c','d'])
d1

a    1
b    2
c    3
d    4
dtype: int64

In [50]:
#indexing
d[1]

C:\Users\LOG IN\AppData\Local\Temp\ipykernel_4548\719679795.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  d[1]


np.int64(2)

In [51]:
d['b']

np.int64(2)

In [52]:
#slicing
d[1:4:2]

b    2
d    4
dtype: int64

In [53]:
d['b':'d':2]

b    2
d    4
dtype: int64

# PIL - "python imaging library
<pre><b>it provides the python interpreter with image editing capabilities</pre>

In [2]:
#to import PIL
from PIL import Image 

In [3]:
#to read an image 
a = Image.open(r"C:\Users\LOG IN\Downloads\Grosser_Panda.jpg")


In [4]:
type(a)

PIL.JpegImagePlugin.JpegImageFile

In [5]:
a.format

'JPEG'

#### we can edit the image using this